### ISSUE TITLE
В имени класса может быть только один модификатор. Т.е. такие имена section__title_align_center - не хорошо)

### ISSUE THREAD

**Issue by igosheva** [skuralov10/burgers#13]
https://github.com/skuralov10/burgers/blob/c4c18db469dc925fc35c33aa797105dd3d3d14aa/index.html#L56

**Comment by skuralov10** [comment]
нам так советовал сделать Вова Сабанцев, говорил что если мы меняем одно свойство, то лучше его сделать с таким классом.
